#include "stm32f0xx.h"
#include "stm32f0_discovery.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

//bit values for display
#define RED 3
#define RED0 1
#define RED1 2
#define BLUE 12
#define BLUE0 4
#define BLUE1 8
#define GREEN 48
#define GREEN0 16
#define GREEN1 32
#define WHITE 63
#define WHIT0 21
#define WHIT1 42
#define PURPLE 15
#define PURPLE0 5
#define PURPLE1 10
#define ORANGE 51
#define ORANGE0 17
#define ORANGE1 34
#define TEAL 60
#define TEAL0 20
#define TEAL1 40
#define BLANK 0
#define BLANK0 21
#define BLANK1 42
#define SIZE 64

//digit values are 15 bits to represent 5 row 3 column LED display of a number - least significant bit represents top right in 5x3 and most significant represents bottom left
#define ONE 0x3E0
#define TWO 0x76B7
#define THREE 0x7EB5
#define FOUR 0x7C9C
#define FIVE 0x5EBD
#define SIX 0x5EBF
#define SEVEN 0x7E10
#define EIGHT 0x7EBF
#define NINE 0x7E9C
#define ZERO 0x7E3F

//array of digit bit values
int num5x3s[10] = {ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE};

u_int8_t flapper[64] = {BLANK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLANK, ORANGE, ORANGE, ORANGE, ORANGE, BLANK, BLANK, BLANK, BLANK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLANK, BLANK, BLANK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, WHITE, WHITE, WHITE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, WHITE, BLANK, WHITE, ORANGE, ORANGE, ORANGE, ORANGE, RED, RED, BLANK, BLANK, BLANK, BLANK, ORANGE, BLANK, RED, BLANK, BLANK, BLANK, BLANK};

int current;
int width;
int row;
int col;

int VERTPIX = 64;  //number of LEDS
int HORIZPIX = 64;  //number of LEDS
int BARWIDTH = 8;  //barrier BARWIDTH
int VGAP = 30;  //gap between top and bottom for bird to fly through
int HGAP = 40;  //gap between barriers
int PIXBITS = 1;  //bits per pixel
int BIRDWIDTH = 8;  //width of bird
int BIRDHEIGHT = 8;  //height of bird
int BIRDJUMP = 12;
int JUMPHEIGHT = 16;
int SCORE = 0;
int BACKBIRD = 16;
int NUMROW = 0;  //location for score
int NUMCOL = 0;
int LDRNUMCOL = 30;
int NUM[1][11] = {0};
int display[2][64];
u_int8_t colordisplay[32][64];
int BIRD[3][64];
int combined[2][64];
int MODE = 0;
int STARTHEIGHT = 32;
int BIRDY;
int SCORE1;
int SCORE2;
int SCORE3;
int POSITION = 0;
int ENDD0 = RED0;


void endgame(void);
void birdgenerator(void);
void setdisplay(void);
void nano_wait(int);
void nano_wait(int);
void latch(int);
void setRow(int);

void nano_wait(int n) {
    asm(    "        mov r0,%0\n"
            "repeat: sub r0,#83\n"
            "        bgt repeat\n" : : "r"(n) : "r0", "cc");
}

void barriergenerator(){
	int lower;  //highest vertical component of lower barrier
	int upper;  //lowest of upper
	int nextcolumn[2][1];  //the next vertical column not currently being displayed
	int ITERWIDTH = BARWIDTH + HGAP;  //number of pixels wide one cycle is

	int loop;  //loops through iteration
	int barloop;  //creates barrier
	int loop2;
	int scorehelper = 0;

	POSITION = 0;

	for(loop = 0; loop < 2; loop++){
		for(loop2 = 0; loop2 < 64; loop2++){
			display[loop][loop2] = 0;
		}
	}
	SCORE = 0;
	while(MODE == 1){
		lower = ((TIM3 -> CNT) % (64 - VGAP- 2)) + 1;  //TIM3 -> CNT generates random sequence
		upper = lower + VGAP;
		//nano_wait(100000000);

		for(loop = 0; loop < ITERWIDTH; loop++){
			nano_wait(1000000);
			POSITION = loop;

			if(loop < HGAP){
				for(barloop = 0; barloop < 64; barloop++){
					nextcolumn[barloop / 32][0] &= ~(1 << barloop % 32);
				}
			}
			else if(loop == HGAP || loop == ITERWIDTH - 1){
				for(barloop = 0; barloop < lower - 3; barloop++){
					nextcolumn[barloop / 32][0] &= ~(1 << barloop % 32);
				}  //sets parameters for lower barrier in next column
				for(; barloop < lower; barloop++){
					nextcolumn[barloop / 32][0] |= 1 << barloop % 32;
				}  //sets parameters for lower barrier in next column
				for(barloop = 0; barloop < VGAP; barloop++){
					nextcolumn[(lower + barloop) / 32][0] &= ~(1 << ((lower + barloop) % 32));
				}  //sets parameters for gap in next column
				for(barloop = upper; barloop < upper + 3; barloop++){
					nextcolumn[barloop / 32][0] |= 1 << barloop % 32;
				}  //sets parameters for upper barrier in next column
				for(; barloop < 64; barloop++){
					nextcolumn[barloop / 32][0] &= ~(1 << barloop % 32);
				}  //sets parameters for upper barrier in next column
			}
			else{
				for(barloop = 0; barloop < lower; barloop++){
					nextcolumn[barloop / 32][0] |= 1 << barloop % 32;
				}  //sets parameters for lower barrier in next column
				for(barloop = 0; barloop < VGAP; barloop++){
					nextcolumn[(lower + barloop) / 32][0] &= ~(1 << ((lower + barloop) % 32));
				}  //sets parameters for gap in next column
				for(barloop = upper; barloop < 64; barloop++){
					nextcolumn[barloop / 32][0] |= 1 << barloop % 32;
				}  //sets parameters for upper barrier in next column
			}

			for(barloop = 0; barloop < 63; barloop++){
				for(loop2 = 0; loop2 < 2; loop2++){
					display[loop2][barloop] = display[loop2][barloop + 1];
				}
			}
			for(loop2 = 0; loop2 < 2; loop2++){
				display[loop2][63] = nextcolumn[loop2][0];
			}
			scorehelper++;
			if(scorehelper / (HORIZPIX - BACKBIRD - BIRDWIDTH)){
				SCORE = (scorehelper - (HORIZPIX - BACKBIRD - BIRDWIDTH)) / ITERWIDTH;
			}
			setdisplay();
		}
	}
}




void GPIO_init(){
	//Red (PA1, PA2), Blue (PA3,PA4), Green (PA5,PA6)
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;

	GPIOA->MODER &= ~0xFFFF;
	GPIOA->MODER |= 0x1554; //Output

	//ABCDE - PC0, PC1, PC2, PC3, PC4
	RCC->AHBENR |= RCC_AHBENR_GPIOCEN;

	GPIOC->MODER &= ~0x3FF;
	GPIOC->MODER |= 0x155;

	//OE (PB0), Latch (PB1), CLK (PB3)
	RCC->AHBENR |= RCC_AHBENR_GPIOBEN;

	GPIOB->MODER &= ~(0xF | 0x3<<(2*3));
	GPIOB->MODER |= 0x1<<(2*0); //PB0 Output
	GPIOB->MODER |= 0x1<<(2*1); //PB1 Output
    GPIOB->MODER |= 0x1<<(2*3); //PB3 Output

    GPIOB->ODR |= 0x1; //Turn off OE
}

/*---------------------------------------------------*/
/*This function toggles the latch and turns on the OE*/
/*---------------------------------------------------*/
void latch(int row){
    GPIOB->ODR |= 0x1; //Turn off OE
    //nano_wait(1000);

    GPIOB -> BSRR |= 0x2; //Latch
    nano_wait(1000);
    GPIOB -> BSRR |= 0x2 << 16;
    nano_wait(1000);

    setRow(row);

    GPIOB->ODR &= ~0x1; //Turn on OE
    //nano_wait(1000);
}

void get_color(int color){
    GPIOA->ODR &= ~(0x7E);
    GPIOA->ODR |= color << 1;
    //if((color == BLANK0) || (color == BLANK1)){
    //    GPIOA->ODR &= ~(color << 1);
    //}
}

void setRow(int row){
    GPIOC->BSRR |= 0xFF<<16; //Reset 1-5 of BR
    GPIOC->BSRR |= row; //Row 1 & 32
}

//determines how to write an up to 3 digit number on the screen
void num(int number){
	int mask = 0x1F;
	int loop;
	for(loop = 0; loop < 11; loop++){
		NUM[0][loop] = 0;
	}
	if(number / 100){
		for(loop = 0; loop < 3; loop++){
			NUM[0][loop + 8] = mask & (num5x3s[(number / 100) % 10] >> (5 * (2 - loop)));
		}
	}
	if(number / 10){
		for(loop = 0; loop < 3; loop++){
			NUM[0][loop + 4] = mask & (num5x3s[(number / 10) % 10] >> (5 * (2 - loop)));
		}
	}
	if(number){
		for(loop = 0; loop < 3; loop++){
			NUM[0][loop] = mask & (num5x3s[number % 10] >> (5 *(2 - loop)));
		}
	}
}

//writes display based on number, barriers, and bird
void setdisplay(void){
	int clk = 0;
	int x, y, z;
	int index = 0;
	int BC0 = GREEN0;
	int BC1 = GREEN1;
	//int NC0 = RED0;
	int NC1 = WHIT1;
	//int FC0 = ORANGE0;
	//int FC1 = ORANGE1;
	for(x = 0; x < 32; x++){
		for(y = 0; y < 64; y++){
			colordisplay[x][y] = 0;
		}
	}
	num(SCORE);
	for(x = 0; x < 2; x++){
		for(y = 0; y < 64; y++){
			if((display[x][y] & BIRD[x][y]) || ((BIRDY > 63) && (POSITION >= HGAP))){
				MODE = 2;
			}
			//combined[x][y] = display[x][y] | BIRD[x][y];
		}
	}
	//for(y = 0; y < 11; y++){
		//combined[NUMROW / 32][63 - (y + NUMCOL)] |= NUM[0][y] << NUMROW % 32;
	//}


	//convert existing matrix to combined with row 0 corresponding to top row and 32nd vertical, column 0 on left
	for(y = 0; y < 64; y++){
		x = 0;
		for(z = 0; z < 32; z++){
			if(BIRD[1][y] & (1 << z)){
				colordisplay[z][y] |= flapper[index] & WHIT0;
				index++;
			}
			else if(display[1][y] & (1 << z)){
				colordisplay[z][y] |= BC0;
			}
		}
		x = 1;
		for(z = 0; z < 32; z++){
			if((NUM[0][y] & (1 << z)) && (y < 11)){
				if(z < 5){
					colordisplay[NUMROW + z][63 - (y - NUMCOL)] |= NC1;
				}
			}
			else if(BIRD[0][y] & (1 << z)){
				colordisplay[z][y] |= flapper[index] & WHIT1;
				index++;
			}
			else if(display[0][y] & (1 << z)){
				colordisplay[z][y] |= BC1;
			}
		}

	}

    int row;
    int col;
    int rowSize = 32;
    int colSize = 64;
    int color;
    for(row = 0; row < rowSize; row++){
        for(col = 0; col < colSize; col++){
            color = colordisplay[row][63 - col];
            color = ((0x2A & color) >> 1) | ((0x15 & color) << 1);
            get_color(color);
            GPIOB -> BSRR |= 0x8; //CLK ON
            //nano_wait(1000);
            GPIOB -> BSRR |= 0x8 << 16; //CLK OFF
            //nano_wait(1000);
            clk++;
            if (clk == 64){
                clk = 0;
                latch(row);
            }
        }
    }
}

void EXTI0_1_IRQHandler(void){
	EXTI -> PR |= EXTI_PR_PR0;
	if(MODE == 0){
		BIRDY = STARTHEIGHT;
		MODE = 1;
	}
	else if(MODE == 1){
		BIRDY += JUMPHEIGHT / 3;
		birdgenerator();
		BIRDY += JUMPHEIGHT / 3;
		birdgenerator();
		BIRDY += JUMPHEIGHT / 3;
		birdgenerator();
	}
	else{
		MODE = 0;
	}
}

void jump(void){
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	EXTI -> IMR |= EXTI_IMR_MR0;
	EXTI -> RTSR |= EXTI_RTSR_TR0;
	NVIC -> ISER[0] |= 1 << EXTI0_1_IRQn;
}

void TIM2_IRQHandler(void){
	TIM2 -> SR &= ~TIM_SR_UIF;
	if(MODE == 1){
		BIRDY --;
		if(BIRDY < 0){
			MODE = 2;
		}
		birdgenerator();
	}
}

void TIM3_init(void){
	RCC -> APB1ENR |= RCC_APB1ENR_TIM3EN;
	TIM3 -> ARR = 1234;
	TIM3 -> PSC = 987;
	TIM3 -> CR1 |= TIM_CR1_CEN;
}

void TIM2_init(void){
	RCC -> APB1ENR |= RCC_APB1ENR_TIM2EN;
	TIM2 -> ARR = 1999;
	TIM2 -> PSC = 999;
	TIM2 -> DIER |= TIM_DIER_UIE;
	TIM2 -> CR1 |= TIM_CR1_CEN;
	NVIC -> ISER[0] |= 1 << TIM2_IRQn;
}

void birdgenerator(void){
	int loop, loop2;
	for(loop = 0; loop < 63; loop++){
		for(loop2 = 0; loop2 < 2; loop2++){
			BIRD[loop2][loop] = 0;
		}
	}
	for(loop = BACKBIRD; loop < BACKBIRD + BIRDWIDTH; loop++){
		for(loop2 = BIRDY; loop2 < BIRDY + BIRDHEIGHT; loop2++){
			BIRD[loop2 / 32][loop] |= 1 << (loop2 % 32);
		}
	}
	setdisplay();
}

//displays flappy bird intro screen - need to finish "bird" and flashing "push to start"
void intro(void){
    uint8_t homescreen[32][64] = {
            {TEAL, TEAL, TEAL, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL0, ORANGE1 | TEAL0, WHIT1 | TEAL0, WHIT1 | TEAL0, WHIT1 | TEAL0, ORANGE1 | TEAL0, TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, TEAL0, TEAL0, TEAL0, TEAL0, TEAL0, TEAL0, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL},
            {TEAL, TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, TEAL0, RED1 | TEAL0, RED1 | TEAL0, RED1 | TEAL0, RED1 | TEAL0, RED1 | TEAL0, RED1 | TEAL0, TEAL0, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL},
            {TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL0, TEAL0, TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, TEAL0, RED1 | TEAL0, TEAL0, TEAL0, TEAL0, TEAL0, TEAL0, TEAL0, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, TEAL0, RED1 | TEAL0, RED1 | TEAL0, RED1 | TEAL0, RED1 | TEAL0, RED1 | TEAL0, TEAL0, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL0, TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, ORANGE1 | TEAL0, TEAL0, TEAL0, TEAL0, TEAL0, TEAL0, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0, PURPLE0, PURPLE0, PURPLE0, TEAL0, TEAL, TEAL, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, PURPLE0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | PURPLE1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | PURPLE1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | PURPLE1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | PURPLE1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | PURPLE1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | PURPLE1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | PURPLE1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, PURPLE0 | PURPLE1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | PURPLE1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | PURPLE1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | PURPLE1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | PURPLE1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, PURPLE0 | TEAL1, TEAL, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | PURPLE1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | PURPLE1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | PURPLE1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | PURPLE1, TEAL, PURPLE0 | PURPLE1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | PURPLE1, PURPLE0 | TEAL1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | PURPLE1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | PURPLE1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, TEAL0 |PURPLE1, TEAL0 |PURPLE1, TEAL0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | PURPLE1, PURPLE0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 |PURPLE1},
            {PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, TEAL, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | PURPLE1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, TEAL0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | PURPLE1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | PURPLE1, PURPLE0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, TEAL, TEAL, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | PURPLE1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | PURPLE1, PURPLE0 | PURPLE1, PURPLE0 | PURPLE1, TEAL0 |PURPLE1, TEAL0 |PURPLE1, TEAL0 |PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | PURPLE1, PURPLE0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 |PURPLE1},
            {TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, PURPLE0 | PURPLE1, PURPLE0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, PURPLE0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, PURPLE0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 |PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, PURPLE0 | WHIT1, WHIT0 | WHIT1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, PURPLE0 | PURPLE1, PURPLE0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 |PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 |PURPLE1},
            {TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | PURPLE1, PURPLE0 | PURPLE1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | TEAL1, PURPLE0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, PURPLE0 | PURPLE1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | WHIT1, PURPLE0 | PURPLE1, PURPLE0 | TEAL1, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL1, TEAL1, PURPLE1, BLANK0 | WHIT1, BLANK0 | WHIT1, BLANK0 | WHIT1, BLANK0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL1, TEAL1, ORANGE0 | TEAL1, ORANGE0 | PURPLE1, ORANGE0 | WHIT1, BLANK0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, BLANK0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL1, ORANGE0 | TEAL1, ORANGE0 | TEAL1, ORANGE0 | TEAL1, ORANGE0 | PURPLE1, BLANK0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, BLANK0 |WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL1, TEAL1, TEAL1, TEAL1, ORANGE0 | TEAL1, ORANGE0 | TEAL1, ORANGE0 | TEAL1, PURPLE1, WHIT0 | WHIT1, WHIT0 | WHIT1, WHIT0 | WHIT1, BLANK0 | WHIT1, WHIT0 | WHIT1, BLANK0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1,TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1, TEAL, TEAL, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | WHIT1, TEAL0 | PURPLE1},
            {TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, TEAL1, ORANGE0 | TEAL1, ORANGE0 | PURPLE1, PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, PURPLE1, WHIT0 | PURPLE1, PURPLE1, PURPLE1, TEAL, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1},
            {TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, WHIT0 | TEAL1, TEAL1, ORANGE0 | PURPLE1, ORANGE0 | PURPLE1, PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, WHIT0 | PURPLE1, PURPLE1, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL0 | PURPLE1, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL, TEAL0 | PURPLE1, TEAL0 |PURPLE1, TEAL0 |PURPLE1, TEAL0 |PURPLE1, TEAL0 |PURPLE1, TEAL0 |PURPLE1, TEAL0 |PURPLE1, TEAL0 |PURPLE1},
    };

    int row;
    int col;
    int rowSize = 32;
    int colSize = 64;
    int color;
    int clk = 0;
    while(MODE == 0){
    for(row = 0; row < rowSize; row++){
        for(col = 0; col < colSize; col++){
            color = homescreen[31 - row][63 - col];
            color = ((0x2A & color) >> 1) | ((0x15 & color) << 1);
            get_color(color);
            GPIOB -> BSRR |= 0x8; //CLK ON
            //nano_wait(1000);
            GPIOB -> BSRR |= 0x8 << 16; //CLK OFF
            //nano_wait(1000);
            clk++;
            if (clk == 64){
                clk = 0;
                latch(row);
            }
        }
    }
    }
}

//just a function to use when we feel like it
void clearscreen(void){
	int row;
	int col;
	int rowSize = 32;
	int colSize = 64;
	int color;
	int clk = 0;
	while(MODE == 2){
	for(row = 0; row < rowSize; row++){
		for(col = 0; col < colSize; col++){
			color = BLANK;
			get_color(color);
			GPIOB -> BSRR |= 0x8; //CLK ON
			//nano_wait(1000);
			GPIOB -> BSRR |= 0x8 << 16; //CLK OFF
			//nano_wait(1000);
			clk++;
			if (clk == 64){
				clk = 0;
				latch(row);
			}
		}
	}
}
}

void TIM14_init(void){
    RCC -> APB1ENR |= RCC_APB1ENR_TIM14EN;

    TIM14 -> CR1 &= ~(TIM_CR1_CMS | TIM_CR1_DIR); //edge-aligned, upcounting

    TIM14 -> PSC = 48000 - 1; //peripheral clock = 1000 Hz
    TIM14 -> ARR = 500 - 1; //interrupt every 1 Hz

    TIM14 -> DIER |= TIM_DIER_UIE; //update interrupt enable
    NVIC -> ISER[0] |= 1 << TIM14_IRQn;
    TIM14 -> CR1 |= TIM_CR1_CEN; //turn on TIM2 clock
}

void TIM14_IRQHandler(void){
    TIM14->SR &= ~TIM_SR_UIF;
    if(ENDD0 == RED0){
    	ENDD0 = BLANK;
    }
    else{
    	ENDD0 = RED0;
    }
}

//game over - currently clears screen but Weston's code will go here - need to add leaderboard with SCORE1, SCORE2, SCORE3, flash game over, display score number
void endgame(void){
	if(SCORE > SCORE1){
		SCORE3 = SCORE2;
		SCORE2 = SCORE1;
		SCORE1 = SCORE;
	}
	else if(SCORE > SCORE2){
		SCORE3 = SCORE2;
		SCORE2 = SCORE;
	}
	else if(SCORE > SCORE3){
		SCORE3 = SCORE;
	}
	//clearscreen();
    int row;
    int col;
    int rowSize = 32;
    int colSize = 64;
    int color;
    int clk = 0;
    while(MODE == 2){
		uint8_t endscreen[32][64] = {
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, ENDD0, ENDD0, ENDD0, ENDD0, BLANK, ENDD0, ENDD0, ENDD0, ENDD0, BLANK, ENDD0, ENDD0, BLANK, ENDD0, ENDD0, BLANK, ENDD0, ENDD0, ENDD0, ENDD0, BLANK, BLANK, BLANK, BLANK, ENDD0, ENDD0, ENDD0, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, ENDD0, BLANK, ENDD0, ENDD0, ENDD0, ENDD0, BLANK, ENDD0, ENDD0, ENDD0, ENDD0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, ENDD0, BLANK, BLANK, BLANK, BLANK, ENDD0, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, ENDD0, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, ENDD0, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, BLANK, ENDD0, BLANK, BLANK, ENDD0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, ENDD0, BLANK, BLANK, BLANK, BLANK, ENDD0, ENDD0, ENDD0, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, ENDD0, BLANK, ENDD0, ENDD0, ENDD0, BLANK, BLANK, BLANK, BLANK, BLANK, ENDD0, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, ENDD0, BLANK, ENDD0, ENDD0, ENDD0, BLANK, BLANK, ENDD0, ENDD0, ENDD0, ENDD0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, ENDD0, BLANK, ENDD0, ENDD0, BLANK, ENDD0, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, ENDD0, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, BLANK, ENDD0, ENDD0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, ENDD0, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, ENDD0, BLANK, BLANK, ENDD0, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, ENDD0, BLANK, BLANK, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, ENDD0, ENDD0, ENDD0, ENDD0, BLANK, ENDD0, BLANK, BLANK, ENDD0, BLANK, ENDD0, BLANK, BLANK, BLANK, ENDD0, BLANK, ENDD0, ENDD0, ENDD0, ENDD0, BLANK, BLANK, BLANK, BLANK, ENDD0, ENDD0, ENDD0, ENDD0, BLANK, BLANK, BLANK, ENDD0, BLANK, BLANK, BLANK, ENDD0, ENDD0, ENDD0, ENDD0, BLANK, ENDD0, BLANK, BLANK, ENDD0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT1, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT1, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, BLANK, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHITE, WHIT0, WHIT0, BLANK, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, BLANK, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, BLANK, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, WHIT1, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, WHIT1, BLANK, BLANK, WHIT1, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, WHIT1, WHIT1, WHIT1, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT1, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, WHIT1, WHIT1, WHIT1, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, WHIT1, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, WHIT1, WHIT1, WHIT1, BLANK, WHIT1, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, WHIT1, WHIT1, WHIT1, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, BLANK, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHITE, WHIT0, BLANK, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, BLANK, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT0, BLANK, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, WHIT0, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT1, WHIT1, WHIT1, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT1, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, WHIT1, WHIT1, WHIT1, BLANK, WHIT1, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
				{BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
		};
		num(SCORE);
		for(int y = 0; y < 11; y++){
			for(int z = 0; z < 5; z++){
				if((NUM[0][10 - y] & (1 << z)) && (y < 11)){
					endscreen[32 - (21 + z)][LDRNUMCOL + y] |= WHIT1;
				}
			}
		}
		num(SCORE1);
		for(int y = 0; y < 11; y++){
			for(int z = 0; z < 5; z++){
				if((NUM[0][10 - y] & (1 << z)) && (y < 11)){
					endscreen[32 - (15 + z)][LDRNUMCOL + y] |= WHIT1;
				}
			}
		}
		num(SCORE2);
		for(int y = 0; y < 11; y++){
			for(int z = 0; z < 5; z++){
				if((NUM[0][10 - y] & (1 << z)) && (y < 11)){
					endscreen[32 - (9 + z)][LDRNUMCOL + y] |= WHIT1;
				}
			}
		}
		num(SCORE3);
		for(int y = 0; y < 11; y++){
			for(int z = 0; z < 5; z++){
				if((NUM[0][10 - y] & (1 << z)) && (y < 11)){
					endscreen[32 - (3 + z)][LDRNUMCOL + y] |= WHIT1;
				}
			}
		}
		for(row = 0; row < rowSize; row++){
			for(col = 0; col < colSize; col++){
				color = endscreen[31 - row][64 - col];
				color = ((0x2A & color) >> 1) | ((0x15 & color) << 1);
				get_color(color);
				GPIOB -> BSRR |= 0x8; //CLK ON
				//nano_wait(1000);
				GPIOB -> BSRR |= 0x8 << 16; //CLK OFF
				//nano_wait(1000);
				clk++;
				if (clk == 64){
					clk = 0;
					latch(row);
				}
			}
		}
    }
}


int main(void){
	GPIO_init();
	TIM3_init();
	TIM2_init();
	TIM14_init();
	jump();

	//Toggle between different modes (0 intro, 1 gameplay, 2 game over)
	while(1){
		if(MODE == 0){
			intro();
		}
		else if(MODE == 1){
			BIRDY = STARTHEIGHT;
			barriergenerator();
		}
		else if(MODE == 2){
			endgame();
		}
	}
}
